version: '3'

volumes:
  docker_data:
    name: docker_data

services:
  db:
    container_name: postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - docker_data:/var/lib/postgresql/data